#!/bin/sh
### BEGIN INIT INFO
# Provides:          update
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     S
# Default-Stop:
# Short-Description: dashboard update startup script
### END INIT INFO

export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

DAEMON=/usr/bin/update
DAEMONDIR=/home/root
DAEMONARGS=""
DAEMONENV="
QT_QPA_EGLFS_HIDECURSOR=1
QT_QPA_EGLFS_DISABLE_INPUT=1
"

NAME=update
DESC=update
PIDFILE=/var/run/$NAME.pid

test -x $DAEMON || exit 0

# setup env
if test -z "$DAEMONENV"; then
	echo "No daemon env for dashboard"
else
	export $DAEMONENV
fi

# set GPIO for Hall
echo 18 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio18/direction
echo 20 > /sys/class/gpio/export
echo in > /sys/class/gpio/gpio20/direction
echo both > /sys/class/gpio/gpio20/edge

# set limit temperature for hall
echo 125000 > /sys/class/thermal/thermal_zone0/trip_point_0_temp
echo 125000 > /sys/class/thermal/thermal_zone0/trip_point_1_temp

# change work dir
cd $DAEMONDIR

set -e

case "$1" in
	start)
	echo -n "Starting $NAME: "
	start-stop-daemon -S -b -q -m -p $PIDFILE -x "$DAEMON" -- $DAEMONARGS
	echo "$NAME."
	;;

	stop)
	echo -n "Stopping $NAME: "
	start-stop-daemon -K -x "$DAEMON" -p $PIDFILE
	echo "$NAME."
	;;

	restart|force-reload)
	echo -n "Restarting $NAME: "
	start-stop-daemon -K -x "$DAEMON" -p $PIDFILE
	sleep 1
	start-stop-daemon -S -b -q -m -p $PIDFILE -x "$DAEMON" -- $DAEMONARGS
	echo "$NAME."
	;;

	*)
	echo "Usage: $NAME {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0

